- name: Updating and upgrading apt packages
  apt:
   upgrade: yes
   update_cache: yes

- name: Installation install software-properties-common
  apt: name=software-properties-common

- name: "Repo PHP 7.4"
  apt_repository:
   repo="ppa:ondrej/php"

- name: "Updating the repo"
  apt: update_cache=yes

- name: Installing PHP 7.4
  apt: name=php7.4 state=present

- name: Installing apache2
  apt: name=apache2 update_cache=yes state=latest

- name: Starting the apache2 service
  service:
   name: apache2
   state: started
   enabled: true

- name: Installing Firewalld
  apt: name=firewalld update_cache=yes state=latest

- name: Allow the service from the firewall
  firewalld:
   permanent: yes
   state: enabled
   immediate: yes
   port: 80/tcp
  notify: restart firewalld

- name: Copy index file
  copy:
   src: ./index.php
   dest: /var/www/html
  notify: restart apache2


- name: change the instances hostnames
  become: true
  become_user: root
  shell: bash ./task02.sh
  args:
   executable: /bin/bash

- name: check webserver1 hostname
  shell: ansible 10.128.0.29 -a hostname
  args:
   executable: /bin/bash

- name: check webserver2 hostname
  shell: ansible 10.128.0.30 -a hostname
  args:
   executable: /bin/bash
